# Generated by Django 5.1.3 on 2024-11-18 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SelectedFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateField(default=django.utils.timezone.now)),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=10,
                    ),
                ),
                ("food_name", models.CharField(max_length=100)),
                ("brand_name", models.CharField(blank=True, max_length=100, null=True)),
                ("protein", models.FloatField()),
                ("carbohydrate", models.FloatField()),
                ("fat", models.FloatField()),
            ],
        ),
    ]
