# Generated by Django 5.1.2 on 2024-12-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_fooditem_fdc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.AddField(
            model_name='meal',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
