# Generated by Django 5.1.2 on 2024-11-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_fooditem_meal_mealitem_delete_selectedfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
