# Generated by Django 5.1.2 on 2024-11-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_fooditem_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='fdc_id',
            field=models.CharField(max_length=50),
        ),
    ]
