POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "kevin", "password": "Pass1234!", "email": "kevin@mail.com" }

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ "username": "kevin", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json
Authorization: token 6dc117a2a08da08d16f90e07bc951ac9ec4173df
